version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    labels:
      - "npm"
      - "deps"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
